service: apistarwars

frameworkVersion: "3"

plugins:
  - serverless-apigw-binary
  - serverless-offline

custom:
  apigwBinary:
    types:
      - "*/*"

package:
  individually: true
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  getPlanetsSwapi:
    handler: src/controller/SwapController.getPlanetsSwapi
    events:
      - http:
          path: /swapi/planets/{id}
          method: GET

  getPlanetsAws:
    handler: src/controller/swapController.getPlanetsAws
    events:
      - http:
          path: /aws/planets/{id}
          method: GET

  newPlanetAws:
    handler:  src/controller/swapController.newPlanetAws
    events:
      - http:
          path: /aws/new/planet
          method: POST


  documentation:
    handler: documentation.documentationHandler
    events:
      - http:
          path: /documentation
          method: GET
          cors: true